<a href="https://colab.research.google.com/github/Cuchorico/Entrega1_JimenezFuentesMonsalve/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

cuba = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Presupuesto Estatal de Cuba anual.csv" , sep=";" , encoding="latin-1")

print (cuba["Unnamed: 3"][20:26])
print (cuba["Unnamed: 8"][-2:])

20       Cultura y Deportes
21      $67.993.233.000,00
22      $82.360.817.000,00
23      $97.882.939.000,00
24     $241.856.846.000,00
25     $439.916.708.000,00
Name: Unnamed: 3, dtype: object
26    NaN
27    NaN
Name: Unnamed: 8, dtype: object

In [ ]:
Presupuestodecuba

,ï»¿VALOR EN PESOS CUBANOS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Miles de Millones de $ cubanos,EducaciÃ³n,Seguridad Social,Cultura y Deportes,Ciencia e InnovaciÃ³n,Salud PÃºb. y Asistencia Social,Admin PÃºblica Defensa,Resto,TOTAL,NaN
1,2018,"$8.090,00","$6.200,60","$1.802,10","$95,20","$10.530,70","$8.722,40","$1.944,80","$37.324,80",NaN
2,2019,"$9.357,10","$7.119,90","$2.182,90","$91,10","$11.058,60","$9.557,20","$2.020,10","$41.386,90",NaN
3,2020,"$12.372,10","$9.669,80","$2.594,30","$123,30","$13.059,60","$11.754,00","$2.313,10","$51.886,20",NaN
4,2021,"$132.371,40","$32.802,00","$6.410,20",NaN,"$78.518,00",NO DICE,"$108.974,00","$320.512,00",NaN
5,2022,"$53.468,00","$39.968,00","$11.659,60",NaN,"$66.375,00","$51.461,00","$10.260,40","$233.192,00",NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,*=estimaciÃ³n en base a lo presupuestado en l...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,VALOR EN MILES DE MILLONES CUBANOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Miles de Millones de $ cubanos,EducaciÃ³n,Seguridad Social,Cultura y Deportes,Ciencia e InnovaciÃ³n,Salud PÃºb. y Asistencia Social,Admin PÃºblica Defensa,Resto,TOTAL,NaN
11,2018,"$8.090.000.000,00","$6.200.600.000,00","$1.802.100.000,00","$95.200.000,00","$10.530.700.000,00","$8.722.400.000,00","$1.944.800.000,00","$37.324.800.000,00",NaN
12,2019,"$9.357.100.000,00","$7.119.900.000,00","$2.182.900.000,00","$91.100.000,00","$11.058.600.000,00","$9.557.200.000,00","$2.020.100.000,00","$41.386.900.000,00",NaN
13,2020,"$12.372.100.000,00","$9.669.800.000,00","$2.594.300.000,00","$123.300.000,00","$13.059.600.000,00","$11.754.000.000,00","$2.313.100.000,00","$51.886.200.000,00",NaN
14,2021,"$132.371.400.000,00","$32.802.000.000,00","$6.410.200.000,00",$-,"$78.518.000.000,00",#VALOR!,"$108.974.000.000,00","$320.512.000.000,00",NaN
15,2022,"$53.468.000.000,00","$39.968.000.000,00","$11.659.600.000,00",$-,"$66.375.000.000,00","$51.461.000.000,00","$10.260.400.000,00","$233.192.000.000,00",NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,*=estimaciÃ³n en base a lo presupuestado en l...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,VALOR EN PESOS CHILENO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Miles de Millones de $ cubanos,EducaciÃ³n,Seguridad Social,Cultura y Deportes,Ciencia e InnovaciÃ³n,Salud PÃºb. y Asistencia Social,Admin PÃºblica Defensa,Resto,TOTAL,NaN
21,2018,"$305.235.700.000,00","$233.948.638.000,00","$67.993.233.000,00","$3.591.896.000,00","$397.323.311.000,00","$329.096.152.000,00","$73.377.304.000,00","$1.408.264.704.000,00",NaN
22,2019,"$353.043.383.000,00","$268.633.827.000,00","$82.360.817.000,00","$3.437.203.000,00","$417.240.978.000,00","$360.593.156.000,00","$76.218.373.000,00","$1.561.527.737.000,00",NaN
23,2020,"$466.799.333.000,00","$364.841.554.000,00","$97.882.939.000,00","$4.652.109.000,00","$492.738.708.000,00","$443.478.420.000,00","$87.273.263.000,00","$1.957.666.326.000,00",NaN
24,2021,"$4.994.372.922.000,00","$1.237.619.460.000,00","$241.856.846.000,00",$-,"$2.962.484.140.000,00",#VALOR!,"$4.111.589.020.000,00","$12.092.917.760.000,00",NaN
25,2022,"$2.017.347.640.000,00","$1.507.992.640.000,00","$439.916.708.000,00",$-,"$2.504.328.750.000,00","$1.941.623.530.000,00","$387.124.892.000,00","$8.798.334.160.000,00",NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,*=estimaciÃ³n en base a lo presupuestado en l...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN